In [1]:
import numpy as np

In [7]:
arr4 = np.random.randint(low=1,high=100,size=20).reshape(4,5)

in this function ,we are creating a array in which numbers are  from 1 to 100 ...and digits should be total 20....


In [10]:
arr4

array([[22, 47, 10, 46, 96],
       [85,  1, 22, 83, 59],
       [13, 83, 41, 78, 33],
       [25, 63, 93, 26, 74]])

In [11]:
arr4[0][2]

np.int64(10)

simply means that arra0means first row and 2 means 1 st row third coloumn digit

In [12]:
arr4[0][4]

np.int64(96)

same here too


In [14]:
arr4[0]

array([22, 47, 10, 46, 96])

In [15]:
arr4>5

array([[ True,  True,  True,  True,  True],
       [ True, False,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [19]:
arr4[arr4>50]

array([96, 85, 83, 59, 83, 78, 63, 93, 74])

by this function the digit which is greater than 50 in   arrray only that ill be printed out ....

In [22]:
arr4[(arr4>50)&(arr4%2!=0)]

array([85, 83, 59, 83, 63, 93])

in array digits which are greater than 50 and also not divisible by 2 ...print it

In [23]:
arr4[(arr4>50)&(arr4%2!=0)] = 0

In [25]:
arr4

array([[22, 47, 10, 46, 96],
       [ 0,  1, 22,  0,  0],
       [13,  0, 41, 78, 33],
       [25,  0,  0, 26, 74]])

which elements are greater than 50 and not divisible by 2 ..change that elements in 0..