<a href="https://colab.research.google.com/github/HemantMishra2003/important-concept-of-python-libraries-/blob/main/numpy_properties_and_attributes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np

In [6]:
arr2=np.array([[1,2,3] , [4,5,6]])

In [7]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
arr2.shape

(2, 3)

In [10]:
arr11 = np.array([[[1,2],[3,4]],[[5,6] ,[7,8]]])

In [11]:
arr11

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [12]:
arr11.shape

(2, 2, 2)

here 3 means it 3 d array

In [13]:
arr11.ndim

3

In [14]:
arr11.size

8

there is difrence between size and itemsize but here not clarify ...find it by your own

In [15]:
arr11.itemsize

8

In [17]:
arr11.dtype

dtype('int64')

by below function arry11  function become float previously it was int type

In [18]:
arr11.astype('float')

array([[[1., 2.],
        [3., 4.]],

       [[5., 6.],
        [7., 8.]]])