In [ ]:
import numpy as np

In [ ]:
arr1 = np.array([1,2,3,4,5,6])

In [ ]:
arr2=np.array([4,5,6,7,8,9])

In [ ]:
arr2 - arr1

array([3, 3, 3, 3, 3, 3])

In [ ]:
arr1*arr2

array([ 4, 10, 18, 28, 40, 54])

In [ ]:
arr1*2

array([ 2,  4,  6,  8, 10, 12])

In [ ]:
arr2>3

array([ True,  True,  True,  True,  True,  True])

In [ ]:
arr2<3

array([False, False, False, False, False, False])

In [ ]:
arr3=np.arange(6).reshape(2,3)

this just above numpy syntax is very important...this syntax is to create matrix....here (6) means digit should be from 0 to 5

In [ ]:
arr3

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
arr4 = np.arange(6,12).reshape(2,3)

here 6 to 12 means digit should be between form 6 to 12 in matrix

In [ ]:
arr4

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
arr4 - arr3

array([[6, 6, 6],
       [6, 6, 6]])

In [ ]:
arr3.dot(arr4)

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

this would not work because arr3 row should be equal to cloumn of 4 ...but here not eqaul...its basic matrix concept of multiplication of two matrix ...m*n = n*p

In [ ]:
arr3=np.arange(6).reshape(2,3)

In [ ]:
arr3

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
arr4 = np.arange(6,12).reshape(3,2)

In [ ]:
arr4

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [ ]:
arr4.max()

np.int64(11)

just above because in matrix 11 ih highest digit

In [ ]:
arr4.min()

np.int64(6)

just above in int64(6) ,and  6 means that  its lowest in the matrix.

In [ ]:
arr4.min(axis=0)

array([6, 7])

did not get later would i do .....

In [ ]:
arr4.min(axis=1)

array([ 6,  8, 10])

agin i did not get just above ...later would do...


In [ ]:
arr4 = np.arange(6,12).reshape(3,2)

In [ ]:
arr4

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [120]:
arr4.sum(axis = 0)

array([24, 27])

again i  did not get this function

In [121]:
arr4.mean()

np.float64(8.5)

agin i did not  get this function

In [ ]:
arr3.dot(arr4)

array([[ 28,  31],
       [100, 112]])

In [122]:
arr4.std()

np.float64(1.707825127659933)

this function is telling about standard deviation  of all array

In [123]:
np.sin(arr4)

array([[-0.2794155 ,  0.6569866 ],
       [ 0.98935825,  0.41211849],
       [-0.54402111, -0.99999021]])

well ,all this function u get deeply by studying oops ...

In [124]:
np.exp(arr4)

array([[  403.42879349,  1096.63315843],
       [ 2980.95798704,  8103.08392758],
       [22026.46579481, 59874.1417152 ]])

In [ ]:
arr6 = np.array([1,2,3])

In [ ]:
arr6

array([1, 2, 3])

In [ ]:
arr5=np.array([[1,2,3] , [4,5,6]])

In [ ]:
arr5

array([[1, 2, 3],
       [4, 5, 6]])