In [1]:
import numpy as np

In [2]:
a1 = np.arange(8).reshape(2,4)

In [3]:
a1

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [7]:
a2 = np.arange(8,16).reshape(2,4)

In [8]:
a2

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [9]:
a1+a2

array([[ 8, 10, 12, 14],
       [16, 18, 20, 22]])

we created two array then we succesfully add two arrays

In [10]:
a3 = np.arange(9).reshape(3,3)

In [11]:
a3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [12]:
a4 = np.arange(3).reshape(1,3)

In [13]:
a4

array([[0, 1, 2]])

In [14]:
a3 + a4

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10]])

array 4 have been added to all the  rows of arra3

complete this numpy braodcastig from the lecture 12 of numpy from campus x