<a href="https://colab.research.google.com/github/HemantMishra2003/important-concept-of-python-libraries-/blob/main/numpy_indexing_slicing_iteration.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np

In [5]:
arr12 = np.arange(24).reshape(2,12)

means here are 24 digit and making the array in 2 rows and 12 column

In [40]:
arr12

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [39]:
for i in arr12:
  print (i)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[12 13 14 15 16 17 18 19 20 21 22 23]


In [42]:
arr12 = np.arange(24).reshape(6,4)

In [43]:
arr12

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [46]:
for i in arr12:
  print (i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]
[16 17 18 19]
[20 21 22 23]


In [48]:
for i in np.nditer(arr12):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23


above syntax is for to write down all the digits not according to array or row

In [47]:
arr1 = np.array([1,2,3,4,5])

In [8]:
arr1

array([1, 2, 3, 4, 5])

In [9]:
arr1[3]

np.int64(4)

shyad yahan 4 isliye aaya hai kyonki hum 3 array ko call kar rahe ahi array hmesha 0 se digit ko count karta hai

In [10]:
arr1[2:4]

array([3, 4])

just above logic did not get

In [11]:
arr1[-1]

np.int64(5)

also just above could not get

In [12]:
arr12[1]

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [13]:
arr13=np.arange(24).reshape(6,4)

In [13]:
arr13

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [14]:
arr13[2]

array([ 8,  9, 10, 11])

 in above , we call 2 got 8 , 9 , 10 ,1 1 array  ::it means we got the third row ,row have been stared from 0.

In [15]:
arr13[:,2]

array([ 2,  6, 10, 14, 18, 22])

In [16]:
arr13[3]

array([12, 13, 14, 15])

In [17]:
arr13[:,3]

array([ 3,  7, 11, 15, 19, 23])

jut above is syntax of printing coloum 3.....

In [18]:
arr13[:,1:3]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14],
       [17, 18],
       [21, 22]])

in above we have gotten 2 coloum and 3 rd coloumn also ....3 is writte but 3 means 2 couloumn means in this type syntax last-1 will be output ...for more information ,could visit to part 6 numpy of camapus x

In [20]:
arr13=np.arange(24).reshape(6,4)

In [21]:
arr13

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [22]:
arr13[2:4,1:3]

array([[ 9, 10],
       [13, 14]])

2:4 means row from 2 to 3 ,4 will not be taken ...and 1:3 means coloum ,coloumn 1 to 2 ..3 will not be taken...hence this will be come ....

In [23]:
arr13[3:5,2:4]

array([[14, 15],
       [18, 19]])

In [27]:
arr13[2]

array([ 8,  9, 10, 11])

In [29]:
arr13[2:4]

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [31]:
arr13[1]

array([4, 5, 6, 7])

In [25]:
arr13[:,3]

array([ 3,  7, 11, 15, 19, 23])

In [33]:
arr13[:, [1, 3]]

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11],
       [13, 15],
       [17, 19],
       [21, 23]])

just uper ka syntex jo hai ye coloumn print karne ka treeka hai

In [38]:
arr13[:, [0, 1, 3]]

array([[ 0,  1,  3],
       [ 4,  5,  7],
       [ 8,  9, 11],
       [12, 13, 15],
       [16, 17, 19],
       [20, 21, 23]])