In [ ]:
import numpy as np

In [ ]:
arr4 = np.arange(6,12).reshape(3,2)

In [ ]:
arr4

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [ ]:
arr4.ndim

2

In [ ]:
arr4.ravel()

array([ 6,  7,  8,  9, 10, 11])

this function is use to bring 2d array in 1d array

In [ ]:
arr4.transpose()

array([[ 6,  8, 10],
       [ 7,  9, 11]])

by this function array compltely transposed

In [ ]:
arr5 = np.arange(12,18).reshape(2,3)

In [ ]:
arr5

array([[12, 13, 14],
       [15, 16, 17]])

In [ ]:


arr3=np.arange(6).reshape(2,3)

In [ ]:
arr3

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
np.hstack((arr3,arr5))

array([[ 0,  1,  2, 12, 13, 14],
       [ 3,  4,  5, 15, 16, 17]])

in this function we add two array each horizental

In [ ]:
np.vstack((arr3 ,arr5))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [12, 13, 14],
       [15, 16, 17]])

In [ ]:
np.vsplit(arr3,2)

[array([[0, 1, 2]]), array([[3, 4, 5]])]